### ISSUE TITLE
A dashboard (architecture diagram) that gives an overall picture of the Cloud resources (Accounts, networks and their dependencies).

### ISSUE THREAD

**Issue by can-I-do** [turbot/steampipe-mod-aws-insights#106]
**Is your feature request related to a problem? Please describe.**
it helps to discover and see the big picture of a multi account, multi network, multi... setup.

**Describe the solution you'd like**
I would like to have a dashboard with an architecture diagram of my Account(s). 
AccountId -> VPC and Subnet inside -> EC2 and other instances inside the subnets -> ...

**Additional context**
example arch diagram
![image](https://user-images.githubusercontent.com/60129163/183034452-e851d5a8-0b4d-4820-8ca9-d13842411024.png)

**Comment by cbruno10** [comment]
Hey @can-I-do , we've actually been exploring various ways to visualize relationships in our dashboards. Many of the dashboards are still early, but feedback (and contributions) are welcome:
- Use the latest v0.17.x alpha from https://github.com/turbot/steampipe/tags
- Try the `new-relationship-graphs` branch of the AWS insights mod - https://github.com/turbot/steampipe-mod-aws-insights/tree/new-relationship-graphs

If you get a chance, can you please give the steps above a try, load up some Detail pages, e.g., `EC2 Instance Detail`, and let us know if these are helpful for your use case? Any other feedback is welcome too!
