### ISSUE TITLE
CloudTrail Detail shows multiple trails in the 'overview' panel when using multi-region trails

### ISSUE THREAD

**Issue by johnsmyth** [turbot/steampipe-mod-aws-insights#160]
**Describe the bug**
CloudTrail detail shows multiple trails in the 'overview' panel when using multi-region trails

**Steampipe version (`steampipe -v`)**
steampipe version 0.17.0-alpha.7

**Plugin version (`steampipe plugin list`)**
aws 0.73.0  

**To reproduce**
set up a multi-region trail and view the Cloudtrail Trail Detail page

**Expected behavior**
Overview should have the data once, for the trail in its home region

**Comment by misraved** [comment]
Closed with https://github.com/turbot/steampipe-mod-aws-insights/pull/278
