### ISSUE TITLE
Add Query to list all AWS Accounts within mod resource 'input' and display all resources with the selected targeted aws account? 

### ISSUE THREAD

**Issue by ahkai86** [turbot/steampipe-mod-aws-insights#301]
**Is your feature request related to a problem? Please describe.**
It is not a problem but a feature request, trying to build a customize dashboard which has a mod resource 'input' to display what resources used within the selected AWS account. 

**Describe the solution you'd like**
As above, trying to build a customize dashboard which has a mod resource 'input' to display what resources used within the selected AWS account. 

**Describe alternatives you've considered**
using SQL cmd to display whole list of AWS accounts and from the selected aws account under "dropdown" input, shows the resources.

**Additional context**

**Comment by ahkai86** [comment]
good to have feature for showing compliance and asset discovery under a single dashboard mod "input" =)

**Comment by rajlearner17** [comment]
@ahkai86 I Appreciate trying out Steampipe. Thank you

Specifically, which specific report are you stating here from the existing set? Refer [here](https://hub.steampipe.io/mods/turbot/aws_insights/dashboards)

I see that; you are building a custom dashboard to render resources for a specific configured account. As far as my understanding goes, it is possible to make such a report related to a single account-used asset as long as we can design the required query. I would appreciate it if you could provide more detailed information about your use case or sample code (omitting sensitive parts) to take a look and help you. 

For more details, please refer to this [doc](https://steampipe.io/docs/mods/writing-dashboards).

**Comment by ahkai86** [comment]
Hi @rajlearner17 ! Good Day, appreciate your prompt reply 

Am trying to code a custom dashboard which has "dropdown list" inputs mod and after selecting a target aws account, all the resources available will be displayed

`dashboard "dashboard_testing"  {
  title = "Dashboard - Testing"

  input "aws_account" {
    title = "AWS Accounts"
    sql   = query.aws_account_input.sql
    width = 4
  }`

**Comment by bigdatasourav** [comment]
Apologies, @ahkai86, for the delay in getting back to you.

I believe you want to create a custom dashboard to list all the resources based on the account; here is a similar [dashboard](https://github.com/turbot/steampipe-mod-aws-insights/blob/main/dashboards/ec2/ec2_instance_detail.sp) which you can refer, in this dashboard based on an EC2 arn the dashboard is listing its details.
Here is another reporting [dashboard](https://github.com/turbot/steampipe-mod-aws-insights/blob/main/dashboards/ec2/ec2_instance_report_public_access.sp) which provides a report in table format of `EC2 Instance Public Access`.

You can also find some of the visual sample pages [here](https://hub.steampipe.io/mods/turbot/aws_insights).

Please try out the above and let us know if this works for you or if you need any other help on this.

**Comment by bigdatasourav** [comment]
Hey @ahkai86, We are closing this issue because we have not heard from you. Please feel free to reopen the issue if you want to share or discuss anything.
