### ISSUE TITLE
Remove cost related queries in RDS DB dashboards

### ISSUE THREAD

**Issue by madhushreeray30** [turbot/steampipe-mod-aws-insights#306]
**Describe the bug**

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by misraved** [comment]
Duplicate to https://github.com/turbot/steampipe-mod-aws-insights/issues/189
