### ISSUE TITLE
ERROR: rpc error: code = Unknown desc = table 'aws_ecs_task_definition' column 'status' requires hydrate data from getEcsTaskDefinition

### ISSUE THREAD

**Issue by bjorntheart** [turbot/steampipe-mod-aws-insights#321]
**Describe the bug**

**Steampipe version (`steampipe -v`)**
```
Steampipe v0.20.10
```

**Plugin version (`steampipe plugin list`)**
```
+--------------------------------------------------+---------+-------------+
| Installed Plugin                                 | Version | Connections |
+--------------------------------------------------+---------+-------------+
| hub.steampipe.io/plugins/turbot/aws@latest       | 0.115.0 | aws         |
| hub.steampipe.io/plugins/turbot/ipinfo@latest    | 0.1.0   | ipinfo      |
| hub.steampipe.io/plugins/turbot/steampipe@latest | 0.8.0   | steampipe   |
+--------------------------------------------------+---------+-------------+
```

**To reproduce**
Run `steampipe dashboard` locally and go to `http://localhost:9194/aws_insights.dashboard.ecs_cluster_detail`

**Expected behavior**
That viewing ECS cluster detail shouldn't fail on ECS task definitions

**Comment by graza-io** [comment]
Hey @bjorntheart 

Sorry you've hit this, potentially could just be a temporary thing that needs you to retry/refresh in a minute or two.

If it's more persistent than this would you be able to capture some more detailed logs, you can enable this with an `env var` like:
```
STEAMPIPE_LOG_LEVEL=debug steampipe dashboard
```

The logs can be found in `~/.steampipe/logs` and will be in format of `plugin-YYYY-MM-DD.log` & `database-YYYY-MM-DD.log`, these could be helpful in determining the issue you're having.

**Comment by bjorntheart** [comment]
@graza-io this is my database log. I redacted sensitive information. The file is relatively small so it was easy, but the plugin log is 63M so still parsing that.  
[database-2023-08-15.log](https://github.com/turbot/steampipe-mod-aws-insights/files/12344997/database-2023-08-15.log)

**Comment by graza-io** [comment]
@bjorntheart - great thanks so much those'll be helpful!

I see a lot of throttling/timeouts going on here, this is something we're actively looking into with the wider team, in the meantime if you could attempt to run the dashboard with the `--max-parallel` arg set to 3 (or via env var `STEAMPIPE_MAX_PARALLEL=3 steampipe dashboard` does this help alleviate the throttling enough that you get results?
**NOTE:** Setting the max parallel will make the dashboards take longer to run but hopefully help them complete for you while we look more into the issues

**Comment by bjorntheart** [comment]
Like you said, it's taking a longer time, and haven't finished yet, but here are some errors from the UI
```
node: container_dashboard_ecs_cluster_detail_anonymous_container_1_anonymous_node_2
ERROR: rpc error: code = Unknown desc = table 'aws_ecs_task_definition' column 'inference_accelerators' requires hydrate data from getEcsTaskDefinition, which failed with error operation error ECS: DescribeTaskDefinition, exceeded maximum number of attempts, 9, https response error StatusCode: 400, RequestID: 5b48d28b-cb6c-478c-ac28-b09201c1696d, api error ThrottlingException: Rate exceeded. (SQLSTATE HV000)
edge: launch type
ERROR: rpc error: code = Unknown desc = table 'aws_ecs_task_definition' column 'network_mode' requires hydrate data from getEcsTaskDefinition, which failed with error operation error ECS: DescribeTaskDefinition, exceeded maximum number of attempts, 9, https response error StatusCode: 400, RequestID: b3e44713-0418-4e06-a114-2e63cc5bc97c, api error ThrottlingException: Rate exceeded. (SQLSTATE HV000)
```

**Comment by graza-io** [comment]
I'm just trying to gather some info now, but do you have a lot of ECS tasks/task definitions (rough sizing is ok, doesn't need to be specific)? Any other information about your environment would be useful too (mostly regarding account number, number of resources you're querying against, etc).

There is also potential to increase number or delay for retries using the configuration settings outlined [here](https://hub.steampipe.io/plugins/turbot/aws#configuration) 
See - `max_error_retry_attempts` and `min_error_retry_delay` options.

Also just wanted to say thanks for the patience and testing/responses, really helpful!

**Comment by graza-io** [comment]
@bjorntheart - did you have a change to retry while tinkering with the `max_error_retry_attempts`/`min_error_retry_delay` settings?

We're also looking at some options for client-side limiting to reduce these `Rate Exceeding` throttling errors, will update more on this soon.

**Comment by graza-io** [comment]
Closing as no further response received, next release with new SDK should provide capability to remove these throttling issues.
