### ISSUE TITLE
Error in documentation index markdown img tag.

### ISSUE THREAD

**Issue by chandru89new** [turbot/steampipe-mod-aws-insights#330]
**Describe the bug**
There's a missing `/` in an `img` tag in docs/index.md. Causes the Hub to crash.

**Steampipe version (`steampipe -v`)**
NA

**Plugin version (`steampipe plugin list`)**
Latest

**Comment by khushboo9024** [comment]
https://github.com/turbot/steampipe-mod-aws-insights/pull/331 closed
