### ISSUE TITLE
Add Authentication for Steampipe Dashboard

### ISSUE THREAD

**Issue by hkoushik** [turbot/steampipe-mod-aws-insights#78]
**Is your feature request related to a problem? Please describe.**
It is better to have an authentication layer for the Dashboard as it helps if hosted in a shared env like Cloud

**Describe the solution you'd like**
Create an authentication mechanism to access the Dashboard as it contains sensitive info about the Cloud. Would be safe to host dashboard in a shared environment among devs with authentication in place.

**Comment by johnsmyth** [comment]
@hkoushik  It is unlikely that we will add support for authentication (or TLS for that matter) in the near term.  It would be fairly straightforward to add ssl and authentication yourself using a reverse proxy like envoy, nginx, or haproxy.  This separation allows us to stay focused on our core area of expertise and value (Steampipe features, functionality, plugins, mods).
